// Generated by https://quicktype.io

export interface PokeResponse {
  count:    number;
  next:     string;
  previous: null;
  results:  Small[];
}

export interface Small {
  name: string;
  url:  string;
}
